/**
 * Business Rules
 * @module gc-platform-api-business-rules
 * @license MIT
 */

// This file was automatically generated by the Generate Genesys Cloud Platform API classes utility on 2025-11-26T23:43:17.538Z

// TODO: Implement JSON schema verification for input and output objects
// TODO: Implement HTTP response typedefs

// Set strict mode
"use strict";

// Errors
import { errors } from "../gc-platform-api-client-errors.js";

// Symbols
import { symbols } from "../gc-platform-api-client-symbols.js";

/** @typedef {import("../gc-platform-api-client-class.js").GCPlatformAPIClient} GCPlatformAPIClient */
/** @typedef {import("@jfabello/http-client").HTTPResponse} HTTPResponse */

/**
 * Request to create a new Business Rules Schema
 * @typedef {object} BusinessRulesSchemaCreateRequest
 * @property {JsonSchemaWithDefinitions} jsonSchema - A JSON schema defining the extension to the built-in entity type.
 */
 
/**
 * Request to update an existing Business Rules Schema
 * @typedef {object} BusinessRulesSchemaUpdateRequest
 * @property {number} version - The schema's version, a positive integer. Required for updates.
 * @property {boolean} [enabled] - The schema's enabled/disabled status. A disabled schema cannot be assigned to any other entities, but the data on those entities from the schema still exists.
 * @property {JsonSchemaWithDefinitions} jsonSchema - A JSON schema defining the extension to the built-in entity type.
 */
 
/**
 * @typedef {object} Contractual
 * @property {string} schemaPropertyKey - The contract schema property key that describes the input value of this column.
 * @property {Contractual} [contractual] - The nested contractual definition that is defined by a contract schema, if any.
 */
 
/**
 * @typedef {object} CopyDecisionTableRequest
 * @property {string} name - The name of the newly created decision table. Must be unique
 * @property {string} [description] - The description of newly created decision table.
 */
 
/**
 * @typedef {object} CreateDecisionTableColumnsRequest
 * @property {DecisionTableInputColumnRequest[]} inputs - The input columns of the decision table.
 * @property {DecisionTableOutputColumnRequest[]} outputs - The output columns of the decision table.
 */
 
/**
 * @typedef {object} CreateDecisionTableRequest
 * @property {string} name - The decision table name.
 * @property {string} [description] - The decision table description.
 * @property {string} divisionId - The ID of the division the decision table belongs to.
 * @property {string} schemaId - The ID of the rules schema used by the decision table.
 * @property {CreateDecisionTableColumnsRequest} columns - The column definitions for this decision table.
 */
 
/**
 * @typedef {object} CreateDecisionTableRowRequest
 * @property {number} [rowIndex] - The absolute position of this row in the decision table. Must be an integerstarting from 1, must be positive and less than or equal to the size of the table. If not provided row will be append to the end of the table. 
 * @property {object} inputs - The input values of the row. The key for this map is the column ID the row value relates. Column IDs are available from the decision table entity
 * @property {object} outputs - The output values of the row. The key for this map is the column ID the row value relates. Column IDs are available from the decision table entity
 */
 
/**
 * Must provide a valid value for exactly one of the fields in this class.
 * @typedef {object} DecisionTableColumnDefaultRowValue
 * @property {string} [value] - A default string value for this column, will be cast to appropriate type according to the relevant contract schema property.
 * @property {string[]} [values] - A default list of values for this column, items will be cast to appropriate type according to the relevant contract schema property
 * @property {string} [special] - A default special value enum for this column.
 */
 
/**
 * @typedef {object} DecisionTableExecutionRequest
 * @property {object} inputs - The JSON input data for executing the decision table. Must be valid according to the execution input contract defined on the table. In the case of enum decision table columns the enum options key should be provided as the value, not the enum options label as this can be changed. For business rules queue columns both “queue” and “id” keys will be required regardless of the queue attribute key and these do not change.
 */
 
/**
 * @typedef {object} DecisionTableInputColumnExpression
 * @property {Contractual} contractual - A value that is defined by a contract schema and used to form the left side of a logical condition.
 * @property {string} comparator - A comparator used to join the left and right sides of a logical condition.
 */
 
/**
 * @typedef {object} DecisionTableInputColumnRequest
 * @property {DecisionTableColumnDefaultRowValue} [defaultsTo] - The default row value for this column that will complete the condition expression where no value is provided by a row.
 * @property {DecisionTableInputColumnExpression} expression - The input column condition expression, comprising the left side and comparator of a logical condition in the form of left|comparator|right, where each row of the decision table will provide the right side to form a complete condition
 */
 
/**
 * @typedef {object} DecisionTableOutputColumnRequest
 * @property {DecisionTableColumnDefaultRowValue} [defaultsTo] - The default row value for this column that will be used for an output value where no value  is provided by a row.
 * @property {OutputValue} value - The output data of this column that will be provided by each row.
 */
 
/**
 * A JSON Schema document.
 * @typedef {object} JsonSchemaWithDefinitions
 * @property {string} [id]
 * @property {string} [$schema]
 * @property {string} [title]
 * @property {string} [description]
 * @property {string} [type]
 * @property {string[]} [required]
 * @property {object} [properties]
 * @property {object} [additionalProperties]
 * @property {object} [definitions]
 */
 
/**
 * @typedef {object} OutputValue
 * @property {string} schemaPropertyKey - The contract schema property key that describes the output value of this column.
 * @property {OutputValue[]} [properties] - The nested output properties of this column that will be provided by each row, if any.
 */
 
/**
 * @typedef {object} PutDecisionTableRowRequest
 * @property {object} [inputs] - The full updated input values of the row. The key for this map is the column ID the row value relates. Column IDs are available from the decision table entity
 * @property {object} [outputs] - The full updated output values of the row. The key for this map is the column ID the row value relates. Column IDs are available from the decision table entity
 */
 
/**
 * @typedef {object} RowSearchFilter
 * @property {RowSearchPredicate[]} predicates - The predicates that each row matches in the search results must match
 */
 
/**
 * @typedef {object} RowSearchPredicate
 * @property {string} columnId - The decision table column identifier this predicate applies to
 * @property {string} operator - The search operator for this predicate
 * @property {string} [value] - The value that will be searched for in rows. Exactly one of 'value' or 'special' can be used.
 * @property {string} [special] - The special value that will be searched for in rows. Exactly one of 'value' or 'special' can be used.
 */
 
/**
 * @typedef {object} SearchDecisionTableRowsRequest
 * @property {RowSearchFilter} filter - The filter criteria for searching decision table rows
 */
 
/**
 * Decision table columns will equal the columns contained in this request after the update is performed. If a list of columns types is not provided (i.e. is null) then no update is performed for that column type
 * @typedef {object} UpdateDecisionTableColumnsRequest
 * @property {DecisionTableInputColumnRequest[]} [inputs] - The input columns of the decision table.
 * @property {DecisionTableOutputColumnRequest[]} [outputs] - The output columns of the decision table.
 */
 
/**
 * @typedef {object} UpdateDecisionTableRequest
 * @property {string} [name] - The decision table name.
 * @property {string} [description] - The decision table description.
 * @property {UpdateDecisionTableColumnsRequest} [columns] - The column definitions for this decision table.
 */
 
/**
 * @typedef {object} UpdateDecisionTableVersionRequest
 * @property {UpdateRowIndexRequest} rowIndexUpdate - An update to a decision table version row index, which moves the row to a new position in the table. Execution output is returned based on the first matching row.
 */
 
/**
 * @typedef {object} UpdateRowIndexRequest
 * @property {string} rowId - The row UUID.
 * @property {number} rowIndex - The updated row index. Must be an integer value greater than or equal to 1. Must be less than or equal to x, where x is the number of rows in the decision table version.
 */
 

/**
 * BusinessRules - Business Rules
 * @class BusinessRules
 */
class BusinessRulesAPI {
	// Private instance properties
	#gcPlatformAPIClient = null;

	/**
	 * Constructor for the BusinessRules class
	 * @constructor
	 * @param {GCPlatformAPIClient} gcPlatformAPIClient - The Genesys Cloud Platform API client instance.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_INSTANCE_TYPE_INVALID} If the Genesys Cloud Platform API client instance argument is not an object.
	 */
	constructor(gcPlatformAPIClient) {
		// Check the Genesys Cloud Platform API client instance argument
		if (typeof gcPlatformAPIClient !== "object" || symbols.GCPlatformAPIClient in gcPlatformAPIClient === false) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_INSTANCE_TYPE_INVALID();
		}

		// Initialize the instance properties
		this.#gcPlatformAPIClient = gcPlatformAPIClient;
	}

	/**
	 * Get a decision table
	 * @async
	 * @param {string} tableId - Table ID
	 * @returns {Promise<HTTPResponse>} A promise that settles to the HTTP response of the call to the "/api/v2/businessrules/decisiontables/{tableId}" endpoint.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID} If a path parameter argument is not of the proper type.
	 */
	getBusinessrulesDecisiontable(tableId) {
		const endpointPath = "/api/v2/businessrules/decisiontables/{tableId}";
		const endpointMethod = "GET";

		// Check the path parameters
		if (this.#checkJSONSchemaType(tableId, "string") === false) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "tableId", "string");
		}

		const apiCallOptions = {};
		apiCallOptions.pathParameters = {};
		apiCallOptions.pathParameters.tableId = tableId;

		return this.#gcPlatformAPIClient.queueAPICall(endpointPath, endpointMethod, apiCallOptions);
	}

	/**
	 * Delete a decision table
	 * @async
	 * @param {string} tableId - Table ID
	 * @param {object} query - The query string parameters for the request. An empty object or null is allowed if all query string parameters are optional.
	 * @param {boolean} [query.forceDelete] -  Force delete decision table (under certain conditions)
	 * @returns {Promise<HTTPResponse>} A promise that settles to the HTTP response of the call to the "/api/v2/businessrules/decisiontables/{tableId}" endpoint.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID} If a path parameter argument is not of the proper type.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETERS_TYPE_INVALID} If the query string parameters argument is not of the proper type.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETER_TYPE_INVALID} If a query string parameter is not of the proper type.
	 */
	deleteBusinessrulesDecisiontable(tableId, query) {
		const endpointPath = "/api/v2/businessrules/decisiontables/{tableId}";
		const endpointMethod = "DELETE";

		// Check the path parameters
		if (this.#checkJSONSchemaType(tableId, "string") === false) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "tableId", "string");
		}

		// Check the query string parameters
		if (typeof query !== "object") {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETERS_TYPE_INVALID(endpointPath, endpointMethod, false);
		}

		if (query !== null) {
			if ("forceDelete" in query && this.#checkJSONSchemaType(query["forceDelete"], "boolean") === false) {
				throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "forceDelete", "boolean");
			}
		}

		const apiCallOptions = {};
		apiCallOptions.pathParameters = {};
		apiCallOptions.pathParameters.tableId = tableId;
		apiCallOptions.queryParameters = query;

		return this.#gcPlatformAPIClient.queueAPICall(endpointPath, endpointMethod, apiCallOptions);
	}

	/**
	 * Update a decision table
	 * @async
	 * @param {string} tableId - Table ID
	 * @param {UpdateDecisionTableRequest} body - The body of the request. An empty object or null is allowed if the body is optional.
	 * @returns {Promise<HTTPResponse>} A promise that settles to the HTTP response of the call to the "/api/v2/businessrules/decisiontables/{tableId}" endpoint.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID} If a path parameter argument is not of the proper type.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_REQUEST_BODY_TYPE_INVALID} If the request body argument is not of the proper type.
	 */
	patchBusinessrulesDecisiontable(tableId, body) {
		const endpointPath = "/api/v2/businessrules/decisiontables/{tableId}";
		const endpointMethod = "PATCH";

		// Check the path parameters
		if (this.#checkJSONSchemaType(tableId, "string") === false) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "tableId", "string");
		}

		// Check the body argument
		if (this.#checkJSONSchemaType(body, "object") === false || body === null) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_REQUEST_BODY_TYPE_INVALID(endpointPath, endpointMethod, "object", true);
		}

		const apiCallOptions = {};
		apiCallOptions.pathParameters = {};
		apiCallOptions.pathParameters.tableId = tableId;
		apiCallOptions.body = body;

		return this.#gcPlatformAPIClient.queueAPICall(endpointPath, endpointMethod, apiCallOptions);
	}

	/**
	 * Execute a published decision table
	 * @async
	 * @param {string} tableId - Table ID
	 * @param {DecisionTableExecutionRequest} body - The body of the request. An empty object or null is allowed if the body is optional.
	 * @returns {Promise<HTTPResponse>} A promise that settles to the HTTP response of the call to the "/api/v2/businessrules/decisiontables/{tableId}/execute" endpoint.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID} If a path parameter argument is not of the proper type.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_REQUEST_BODY_TYPE_INVALID} If the request body argument is not of the proper type.
	 */
	postBusinessrulesDecisiontableExecute(tableId, body) {
		const endpointPath = "/api/v2/businessrules/decisiontables/{tableId}/execute";
		const endpointMethod = "POST";

		// Check the path parameters
		if (this.#checkJSONSchemaType(tableId, "string") === false) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "tableId", "string");
		}

		// Check the body argument
		if (this.#checkJSONSchemaType(body, "object") === false || body === null) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_REQUEST_BODY_TYPE_INVALID(endpointPath, endpointMethod, "object", true);
		}

		const apiCallOptions = {};
		apiCallOptions.pathParameters = {};
		apiCallOptions.pathParameters.tableId = tableId;
		apiCallOptions.body = body;

		return this.#gcPlatformAPIClient.queueAPICall(endpointPath, endpointMethod, apiCallOptions);
	}

	/**
	 * Get a decision table version
	 * @async
	 * @param {string} tableId - Table ID
	 * @param {number} tableVersion - Table Version
	 * @returns {Promise<HTTPResponse>} A promise that settles to the HTTP response of the call to the "/api/v2/businessrules/decisiontables/{tableId}/versions/{tableVersion}" endpoint.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID} If a path parameter argument is not of the proper type.
	 */
	getBusinessrulesDecisiontableVersion(tableId, tableVersion) {
		const endpointPath = "/api/v2/businessrules/decisiontables/{tableId}/versions/{tableVersion}";
		const endpointMethod = "GET";

		// Check the path parameters
		if (this.#checkJSONSchemaType(tableId, "string") === false) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "tableId", "string");
		}

		if (this.#checkJSONSchemaType(tableVersion, "integer") === false) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "tableVersion", "integer");
		}

		const apiCallOptions = {};
		apiCallOptions.pathParameters = {};
		apiCallOptions.pathParameters.tableId = tableId;
		apiCallOptions.pathParameters.tableVersion = tableVersion;

		return this.#gcPlatformAPIClient.queueAPICall(endpointPath, endpointMethod, apiCallOptions);
	}

	/**
	 * Delete a decision table version
	 * @async
	 * @param {string} tableId - Table ID
	 * @param {number} tableVersion - Table Version
	 * @returns {Promise<HTTPResponse>} A promise that settles to the HTTP response of the call to the "/api/v2/businessrules/decisiontables/{tableId}/versions/{tableVersion}" endpoint.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID} If a path parameter argument is not of the proper type.
	 */
	deleteBusinessrulesDecisiontableVersion(tableId, tableVersion) {
		const endpointPath = "/api/v2/businessrules/decisiontables/{tableId}/versions/{tableVersion}";
		const endpointMethod = "DELETE";

		// Check the path parameters
		if (this.#checkJSONSchemaType(tableId, "string") === false) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "tableId", "string");
		}

		if (this.#checkJSONSchemaType(tableVersion, "integer") === false) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "tableVersion", "integer");
		}

		const apiCallOptions = {};
		apiCallOptions.pathParameters = {};
		apiCallOptions.pathParameters.tableId = tableId;
		apiCallOptions.pathParameters.tableVersion = tableVersion;

		return this.#gcPlatformAPIClient.queueAPICall(endpointPath, endpointMethod, apiCallOptions);
	}

	/**
	 * Update a decision table version
	 * @async
	 * @param {string} tableId - Table ID
	 * @param {number} tableVersion - Table Version
	 * @param {UpdateDecisionTableVersionRequest} body - The body of the request. An empty object or null is allowed if the body is optional.
	 * @returns {Promise<HTTPResponse>} A promise that settles to the HTTP response of the call to the "/api/v2/businessrules/decisiontables/{tableId}/versions/{tableVersion}" endpoint.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID} If a path parameter argument is not of the proper type.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_REQUEST_BODY_TYPE_INVALID} If the request body argument is not of the proper type.
	 */
	patchBusinessrulesDecisiontableVersion(tableId, tableVersion, body) {
		const endpointPath = "/api/v2/businessrules/decisiontables/{tableId}/versions/{tableVersion}";
		const endpointMethod = "PATCH";

		// Check the path parameters
		if (this.#checkJSONSchemaType(tableId, "string") === false) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "tableId", "string");
		}

		if (this.#checkJSONSchemaType(tableVersion, "integer") === false) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "tableVersion", "integer");
		}

		// Check the body argument
		if (this.#checkJSONSchemaType(body, "object") === false || body === null) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_REQUEST_BODY_TYPE_INVALID(endpointPath, endpointMethod, "object", true);
		}

		const apiCallOptions = {};
		apiCallOptions.pathParameters = {};
		apiCallOptions.pathParameters.tableId = tableId;
		apiCallOptions.pathParameters.tableVersion = tableVersion;
		apiCallOptions.body = body;

		return this.#gcPlatformAPIClient.queueAPICall(endpointPath, endpointMethod, apiCallOptions);
	}

	/**
	 * Copy a decision table version
	 * @async
	 * @param {string} tableId - Table ID
	 * @param {number} tableVersion - Table Version
	 * @param {CopyDecisionTableRequest} body - The body of the request. An empty object or null is allowed if the body is optional.
	 * @returns {Promise<HTTPResponse>} A promise that settles to the HTTP response of the call to the "/api/v2/businessrules/decisiontables/{tableId}/versions/{tableVersion}/copy" endpoint.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID} If a path parameter argument is not of the proper type.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_REQUEST_BODY_TYPE_INVALID} If the request body argument is not of the proper type.
	 */
	postBusinessrulesDecisiontableVersionCopy(tableId, tableVersion, body) {
		const endpointPath = "/api/v2/businessrules/decisiontables/{tableId}/versions/{tableVersion}/copy";
		const endpointMethod = "POST";

		// Check the path parameters
		if (this.#checkJSONSchemaType(tableId, "string") === false) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "tableId", "string");
		}

		if (this.#checkJSONSchemaType(tableVersion, "integer") === false) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "tableVersion", "integer");
		}

		// Check the body argument
		if (this.#checkJSONSchemaType(body, "object") === false || body === null) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_REQUEST_BODY_TYPE_INVALID(endpointPath, endpointMethod, "object", true);
		}

		const apiCallOptions = {};
		apiCallOptions.pathParameters = {};
		apiCallOptions.pathParameters.tableId = tableId;
		apiCallOptions.pathParameters.tableVersion = tableVersion;
		apiCallOptions.body = body;

		return this.#gcPlatformAPIClient.queueAPICall(endpointPath, endpointMethod, apiCallOptions);
	}

	/**
	 * Execute a decision table version
	 * @async
	 * @param {string} tableId - Table ID
	 * @param {number} tableVersion - Table Version
	 * @param {DecisionTableExecutionRequest} body - The body of the request. An empty object or null is allowed if the body is optional.
	 * @returns {Promise<HTTPResponse>} A promise that settles to the HTTP response of the call to the "/api/v2/businessrules/decisiontables/{tableId}/versions/{tableVersion}/execute" endpoint.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID} If a path parameter argument is not of the proper type.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_REQUEST_BODY_TYPE_INVALID} If the request body argument is not of the proper type.
	 */
	postBusinessrulesDecisiontableVersionExecute(tableId, tableVersion, body) {
		const endpointPath = "/api/v2/businessrules/decisiontables/{tableId}/versions/{tableVersion}/execute";
		const endpointMethod = "POST";

		// Check the path parameters
		if (this.#checkJSONSchemaType(tableId, "string") === false) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "tableId", "string");
		}

		if (this.#checkJSONSchemaType(tableVersion, "integer") === false) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "tableVersion", "integer");
		}

		// Check the body argument
		if (this.#checkJSONSchemaType(body, "object") === false || body === null) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_REQUEST_BODY_TYPE_INVALID(endpointPath, endpointMethod, "object", true);
		}

		const apiCallOptions = {};
		apiCallOptions.pathParameters = {};
		apiCallOptions.pathParameters.tableId = tableId;
		apiCallOptions.pathParameters.tableVersion = tableVersion;
		apiCallOptions.body = body;

		return this.#gcPlatformAPIClient.queueAPICall(endpointPath, endpointMethod, apiCallOptions);
	}

	/**
	 * Publish a decision table version
	 * @async
	 * @param {string} tableId - Table ID
	 * @param {number} tableVersion - Table Version
	 * @returns {Promise<HTTPResponse>} A promise that settles to the HTTP response of the call to the "/api/v2/businessrules/decisiontables/{tableId}/versions/{tableVersion}/publish" endpoint.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID} If a path parameter argument is not of the proper type.
	 */
	putBusinessrulesDecisiontableVersionPublish(tableId, tableVersion) {
		const endpointPath = "/api/v2/businessrules/decisiontables/{tableId}/versions/{tableVersion}/publish";
		const endpointMethod = "PUT";

		// Check the path parameters
		if (this.#checkJSONSchemaType(tableId, "string") === false) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "tableId", "string");
		}

		if (this.#checkJSONSchemaType(tableVersion, "integer") === false) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "tableVersion", "integer");
		}

		const apiCallOptions = {};
		apiCallOptions.pathParameters = {};
		apiCallOptions.pathParameters.tableId = tableId;
		apiCallOptions.pathParameters.tableVersion = tableVersion;

		return this.#gcPlatformAPIClient.queueAPICall(endpointPath, endpointMethod, apiCallOptions);
	}

	/**
	 * Update the Business Rules Schema to the latest version for a given decision table version
	 * @async
	 * @param {string} tableId - Table ID
	 * @param {number} tableVersion - Table Version
	 * @returns {Promise<HTTPResponse>} A promise that settles to the HTTP response of the call to the "/api/v2/businessrules/decisiontables/{tableId}/versions/{tableVersion}/sync" endpoint.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID} If a path parameter argument is not of the proper type.
	 */
	postBusinessrulesDecisiontableVersionSync(tableId, tableVersion) {
		const endpointPath = "/api/v2/businessrules/decisiontables/{tableId}/versions/{tableVersion}/sync";
		const endpointMethod = "POST";

		// Check the path parameters
		if (this.#checkJSONSchemaType(tableId, "string") === false) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "tableId", "string");
		}

		if (this.#checkJSONSchemaType(tableVersion, "integer") === false) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "tableVersion", "integer");
		}

		const apiCallOptions = {};
		apiCallOptions.pathParameters = {};
		apiCallOptions.pathParameters.tableId = tableId;
		apiCallOptions.pathParameters.tableVersion = tableVersion;

		return this.#gcPlatformAPIClient.queueAPICall(endpointPath, endpointMethod, apiCallOptions);
	}

	/**
	 * Get a list of decision table versions
	 * @async
	 * @param {string} tableId - Table ID
	 * @param {object} query - The query string parameters for the request. An empty object or null is allowed if all query string parameters are optional.
	 * @param {string} [query.after] -  The cursor that points to the end of the set of entities that has been returned.
	 * @param {string} [query.pageSize] -  Number of entities to return. Maximum of 100.
	 * @returns {Promise<HTTPResponse>} A promise that settles to the HTTP response of the call to the "/api/v2/businessrules/decisiontables/{tableId}/versions" endpoint.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID} If a path parameter argument is not of the proper type.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETERS_TYPE_INVALID} If the query string parameters argument is not of the proper type.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETER_TYPE_INVALID} If a query string parameter is not of the proper type.
	 */
	getBusinessrulesDecisiontableVersions(tableId, query) {
		const endpointPath = "/api/v2/businessrules/decisiontables/{tableId}/versions";
		const endpointMethod = "GET";

		// Check the path parameters
		if (this.#checkJSONSchemaType(tableId, "string") === false) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "tableId", "string");
		}

		// Check the query string parameters
		if (typeof query !== "object") {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETERS_TYPE_INVALID(endpointPath, endpointMethod, false);
		}

		if (query !== null) {
			if ("after" in query && this.#checkJSONSchemaType(query["after"], "string") === false) {
				throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "after", "string");
			}
			if ("pageSize" in query && this.#checkJSONSchemaType(query["pageSize"], "string") === false) {
				throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "pageSize", "string");
			}
		}

		const apiCallOptions = {};
		apiCallOptions.pathParameters = {};
		apiCallOptions.pathParameters.tableId = tableId;
		apiCallOptions.queryParameters = query;

		return this.#gcPlatformAPIClient.queueAPICall(endpointPath, endpointMethod, apiCallOptions);
	}

	/**
	 * Create a new decision table version
	 * @async
	 * @param {string} tableId - Table ID
	 * @returns {Promise<HTTPResponse>} A promise that settles to the HTTP response of the call to the "/api/v2/businessrules/decisiontables/{tableId}/versions" endpoint.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID} If a path parameter argument is not of the proper type.
	 */
	postBusinessrulesDecisiontableVersions(tableId) {
		const endpointPath = "/api/v2/businessrules/decisiontables/{tableId}/versions";
		const endpointMethod = "POST";

		// Check the path parameters
		if (this.#checkJSONSchemaType(tableId, "string") === false) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "tableId", "string");
		}

		const apiCallOptions = {};
		apiCallOptions.pathParameters = {};
		apiCallOptions.pathParameters.tableId = tableId;

		return this.#gcPlatformAPIClient.queueAPICall(endpointPath, endpointMethod, apiCallOptions);
	}

	/**
	 * Get a list of decision tables.
	 * @async
	 * @param {object} query - The query string parameters for the request. An empty object or null is allowed if all query string parameters are optional.
	 * @param {string} [query.after] -  The cursor that points to the end of the set of entities that has been returned.
	 * @param {string} [query.pageSize] -  Number of entities to return. Maximum of 100.
	 * @param {string[]} [query.divisionIds] -  One or more comma separated divisions to filters decision tables by. If nothing is provided, the decision tables associated with the list of divisions that the user has access to will be returned.
	 * @param {string} [query.name] -  Search for decision tables with a name that contains the given search string. Search is case insensitive and will match any table that contains this string in any part of the name.
	 * @returns {Promise<HTTPResponse>} A promise that settles to the HTTP response of the call to the "/api/v2/businessrules/decisiontables" endpoint.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETERS_TYPE_INVALID} If the query string parameters argument is not of the proper type.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETER_TYPE_INVALID} If a query string parameter is not of the proper type.
	 */
	getBusinessrulesDecisiontables(query) {
		const endpointPath = "/api/v2/businessrules/decisiontables";
		const endpointMethod = "GET";

		// Check the query string parameters
		if (typeof query !== "object") {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETERS_TYPE_INVALID(endpointPath, endpointMethod, false);
		}

		if (query !== null) {
			if ("after" in query && this.#checkJSONSchemaType(query["after"], "string") === false) {
				throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "after", "string");
			}
			if ("pageSize" in query && this.#checkJSONSchemaType(query["pageSize"], "string") === false) {
				throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "pageSize", "string");
			}
			if ("divisionIds" in query && this.#checkJSONSchemaType(query["divisionIds"], "array") === false) {
				throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "divisionIds", "array");
			}
			if ("name" in query && this.#checkJSONSchemaType(query["name"], "string") === false) {
				throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "name", "string");
			}
		}

		const apiCallOptions = {};
		apiCallOptions.queryParameters = query;

		return this.#gcPlatformAPIClient.queueAPICall(endpointPath, endpointMethod, apiCallOptions);
	}

	/**
	 * Create a decision table
	 * @async
	 * @param {CreateDecisionTableRequest} body - The body of the request. An empty object or null is allowed if the body is optional.
	 * @returns {Promise<HTTPResponse>} A promise that settles to the HTTP response of the call to the "/api/v2/businessrules/decisiontables" endpoint.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_REQUEST_BODY_TYPE_INVALID} If the request body argument is not of the proper type.
	 */
	postBusinessrulesDecisiontables(body) {
		const endpointPath = "/api/v2/businessrules/decisiontables";
		const endpointMethod = "POST";

		// Check the body argument
		if (this.#checkJSONSchemaType(body, "object") === false || body === null) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_REQUEST_BODY_TYPE_INVALID(endpointPath, endpointMethod, "object", true);
		}

		const apiCallOptions = {};
		apiCallOptions.body = body;

		return this.#gcPlatformAPIClient.queueAPICall(endpointPath, endpointMethod, apiCallOptions);
	}

	/**
	 * Search for decision tables.
	 * @async
	 * @param {object} query - The query string parameters for the request. An empty object or null is allowed if all query string parameters are optional.
	 * @param {string} [query.after] -  The cursor that points to the end of the set of entities that has been returned.
	 * @param {string} [query.pageSize] -  Number of entities to return. Maximum of 100.
	 * @param {string} [query.schemaId] -  Search for decision tables that use the schema with this ID. Cannot be combined with name search. Search results will not be paginated if used.
	 * @param {string} [query.name] -  Search for decision tables with a name that contains the given search string. Search is case insensitive and will match any table that contains this string in any part of the name. Cannot be combined with schema search. Search results will not be paginated if used.
	 * @param {boolean} [query.withPublishedVersion] -  Filters results to only decision tables that have at least one version in Published status
	 * @param {string[]} [query.expand] -  Fields to expand in response
	 * @param {string[]} [query.ids] -  Decision table IDs to search for
	 * @returns {Promise<HTTPResponse>} A promise that settles to the HTTP response of the call to the "/api/v2/businessrules/decisiontables/search" endpoint.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETERS_TYPE_INVALID} If the query string parameters argument is not of the proper type.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETER_TYPE_INVALID} If a query string parameter is not of the proper type.
	 */
	getBusinessrulesDecisiontablesSearch(query) {
		const endpointPath = "/api/v2/businessrules/decisiontables/search";
		const endpointMethod = "GET";

		// Check the query string parameters
		if (typeof query !== "object") {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETERS_TYPE_INVALID(endpointPath, endpointMethod, false);
		}

		if (query !== null) {
			if ("after" in query && this.#checkJSONSchemaType(query["after"], "string") === false) {
				throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "after", "string");
			}
			if ("pageSize" in query && this.#checkJSONSchemaType(query["pageSize"], "string") === false) {
				throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "pageSize", "string");
			}
			if ("schemaId" in query && this.#checkJSONSchemaType(query["schemaId"], "string") === false) {
				throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "schemaId", "string");
			}
			if ("name" in query && this.#checkJSONSchemaType(query["name"], "string") === false) {
				throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "name", "string");
			}
			if ("withPublishedVersion" in query && this.#checkJSONSchemaType(query["withPublishedVersion"], "boolean") === false) {
				throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "withPublishedVersion", "boolean");
			}
			if ("expand" in query && this.#checkJSONSchemaType(query["expand"], "array") === false) {
				throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "expand", "array");
			}
			if ("ids" in query && this.#checkJSONSchemaType(query["ids"], "array") === false) {
				throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "ids", "array");
			}
		}

		const apiCallOptions = {};
		apiCallOptions.queryParameters = query;

		return this.#gcPlatformAPIClient.queueAPICall(endpointPath, endpointMethod, apiCallOptions);
	}

	/**
	 * Get a decision table row
	 * @async
	 * @param {string} tableId - Table ID
	 * @param {number} tableVersion - Table Version
	 * @param {string} rowId - Row ID
	 * @returns {Promise<HTTPResponse>} A promise that settles to the HTTP response of the call to the "/api/v2/businessrules/decisiontables/{tableId}/versions/{tableVersion}/rows/{rowId}" endpoint.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID} If a path parameter argument is not of the proper type.
	 */
	getBusinessrulesDecisiontableVersionRow(tableId, tableVersion, rowId) {
		const endpointPath = "/api/v2/businessrules/decisiontables/{tableId}/versions/{tableVersion}/rows/{rowId}";
		const endpointMethod = "GET";

		// Check the path parameters
		if (this.#checkJSONSchemaType(tableId, "string") === false) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "tableId", "string");
		}

		if (this.#checkJSONSchemaType(tableVersion, "integer") === false) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "tableVersion", "integer");
		}

		if (this.#checkJSONSchemaType(rowId, "string") === false) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "rowId", "string");
		}

		const apiCallOptions = {};
		apiCallOptions.pathParameters = {};
		apiCallOptions.pathParameters.tableId = tableId;
		apiCallOptions.pathParameters.tableVersion = tableVersion;
		apiCallOptions.pathParameters.rowId = rowId;

		return this.#gcPlatformAPIClient.queueAPICall(endpointPath, endpointMethod, apiCallOptions);
	}

	/**
	 * Full update a decision table row
	 * @async
	 * @param {string} tableId - Table ID
	 * @param {number} tableVersion - Table Version
	 * @param {string} rowId - Row ID
	 * @param {PutDecisionTableRowRequest} body - The body of the request. An empty object or null is allowed if the body is optional.
	 * @returns {Promise<HTTPResponse>} A promise that settles to the HTTP response of the call to the "/api/v2/businessrules/decisiontables/{tableId}/versions/{tableVersion}/rows/{rowId}" endpoint.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID} If a path parameter argument is not of the proper type.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_REQUEST_BODY_TYPE_INVALID} If the request body argument is not of the proper type.
	 */
	putBusinessrulesDecisiontableVersionRow(tableId, tableVersion, rowId, body) {
		const endpointPath = "/api/v2/businessrules/decisiontables/{tableId}/versions/{tableVersion}/rows/{rowId}";
		const endpointMethod = "PUT";

		// Check the path parameters
		if (this.#checkJSONSchemaType(tableId, "string") === false) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "tableId", "string");
		}

		if (this.#checkJSONSchemaType(tableVersion, "integer") === false) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "tableVersion", "integer");
		}

		if (this.#checkJSONSchemaType(rowId, "string") === false) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "rowId", "string");
		}

		// Check the body argument
		if (this.#checkJSONSchemaType(body, "object") === false || body === null) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_REQUEST_BODY_TYPE_INVALID(endpointPath, endpointMethod, "object", true);
		}

		const apiCallOptions = {};
		apiCallOptions.pathParameters = {};
		apiCallOptions.pathParameters.tableId = tableId;
		apiCallOptions.pathParameters.tableVersion = tableVersion;
		apiCallOptions.pathParameters.rowId = rowId;
		apiCallOptions.body = body;

		return this.#gcPlatformAPIClient.queueAPICall(endpointPath, endpointMethod, apiCallOptions);
	}

	/**
	 * Delete a decision table row
	 * @async
	 * @param {string} tableId - Table ID
	 * @param {number} tableVersion - Table Version
	 * @param {string} rowId - Row ID
	 * @returns {Promise<HTTPResponse>} A promise that settles to the HTTP response of the call to the "/api/v2/businessrules/decisiontables/{tableId}/versions/{tableVersion}/rows/{rowId}" endpoint.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID} If a path parameter argument is not of the proper type.
	 */
	deleteBusinessrulesDecisiontableVersionRow(tableId, tableVersion, rowId) {
		const endpointPath = "/api/v2/businessrules/decisiontables/{tableId}/versions/{tableVersion}/rows/{rowId}";
		const endpointMethod = "DELETE";

		// Check the path parameters
		if (this.#checkJSONSchemaType(tableId, "string") === false) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "tableId", "string");
		}

		if (this.#checkJSONSchemaType(tableVersion, "integer") === false) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "tableVersion", "integer");
		}

		if (this.#checkJSONSchemaType(rowId, "string") === false) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "rowId", "string");
		}

		const apiCallOptions = {};
		apiCallOptions.pathParameters = {};
		apiCallOptions.pathParameters.tableId = tableId;
		apiCallOptions.pathParameters.tableVersion = tableVersion;
		apiCallOptions.pathParameters.rowId = rowId;

		return this.#gcPlatformAPIClient.queueAPICall(endpointPath, endpointMethod, apiCallOptions);
	}

	/**
	 * Get a list of decision table rows.
	 * @async
	 * @param {string} tableId - Table ID
	 * @param {number} tableVersion - Table Version
	 * @param {object} query - The query string parameters for the request. An empty object or null is allowed if all query string parameters are optional.
	 * @param {string} [query.pageNumber] -  Page number of the entities to return. Defaults to 1.
	 * @param {string} [query.pageSize] -  Number of entities to return. Maximum of 100. Defaults to 25.
	 * @returns {Promise<HTTPResponse>} A promise that settles to the HTTP response of the call to the "/api/v2/businessrules/decisiontables/{tableId}/versions/{tableVersion}/rows" endpoint.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID} If a path parameter argument is not of the proper type.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETERS_TYPE_INVALID} If the query string parameters argument is not of the proper type.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETER_TYPE_INVALID} If a query string parameter is not of the proper type.
	 */
	getBusinessrulesDecisiontableVersionRows(tableId, tableVersion, query) {
		const endpointPath = "/api/v2/businessrules/decisiontables/{tableId}/versions/{tableVersion}/rows";
		const endpointMethod = "GET";

		// Check the path parameters
		if (this.#checkJSONSchemaType(tableId, "string") === false) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "tableId", "string");
		}

		if (this.#checkJSONSchemaType(tableVersion, "integer") === false) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "tableVersion", "integer");
		}

		// Check the query string parameters
		if (typeof query !== "object") {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETERS_TYPE_INVALID(endpointPath, endpointMethod, false);
		}

		if (query !== null) {
			if ("pageNumber" in query && this.#checkJSONSchemaType(query["pageNumber"], "string") === false) {
				throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "pageNumber", "string");
			}
			if ("pageSize" in query && this.#checkJSONSchemaType(query["pageSize"], "string") === false) {
				throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "pageSize", "string");
			}
		}

		const apiCallOptions = {};
		apiCallOptions.pathParameters = {};
		apiCallOptions.pathParameters.tableId = tableId;
		apiCallOptions.pathParameters.tableVersion = tableVersion;
		apiCallOptions.queryParameters = query;

		return this.#gcPlatformAPIClient.queueAPICall(endpointPath, endpointMethod, apiCallOptions);
	}

	/**
	 * Create a decision table row
	 * @async
	 * @param {string} tableId - Table ID
	 * @param {number} tableVersion - Table Version
	 * @param {CreateDecisionTableRowRequest} body - The body of the request. An empty object or null is allowed if the body is optional.
	 * @returns {Promise<HTTPResponse>} A promise that settles to the HTTP response of the call to the "/api/v2/businessrules/decisiontables/{tableId}/versions/{tableVersion}/rows" endpoint.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID} If a path parameter argument is not of the proper type.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_REQUEST_BODY_TYPE_INVALID} If the request body argument is not of the proper type.
	 */
	postBusinessrulesDecisiontableVersionRows(tableId, tableVersion, body) {
		const endpointPath = "/api/v2/businessrules/decisiontables/{tableId}/versions/{tableVersion}/rows";
		const endpointMethod = "POST";

		// Check the path parameters
		if (this.#checkJSONSchemaType(tableId, "string") === false) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "tableId", "string");
		}

		if (this.#checkJSONSchemaType(tableVersion, "integer") === false) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "tableVersion", "integer");
		}

		// Check the body argument
		if (this.#checkJSONSchemaType(body, "object") === false || body === null) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_REQUEST_BODY_TYPE_INVALID(endpointPath, endpointMethod, "object", true);
		}

		const apiCallOptions = {};
		apiCallOptions.pathParameters = {};
		apiCallOptions.pathParameters.tableId = tableId;
		apiCallOptions.pathParameters.tableVersion = tableVersion;
		apiCallOptions.body = body;

		return this.#gcPlatformAPIClient.queueAPICall(endpointPath, endpointMethod, apiCallOptions);
	}

	/**
	 * Search for decision table rows
	 * @async
	 * @param {string} tableId - Table ID
	 * @param {number} tableVersion - Table Version
	 * @param {object} query - The query string parameters for the request. An empty object or null is allowed if all query string parameters are optional.
	 * @param {string} [query.pageNumber] -  Page number of the entities to return. Defaults to 1.
	 * @param {string} [query.pageSize] -  Number of entities to return. Maximum of 100. Defaults to 25.
	 * @param {SearchDecisionTableRowsRequest} body - The body of the request. An empty object or null is allowed if the body is optional.
	 * @returns {Promise<HTTPResponse>} A promise that settles to the HTTP response of the call to the "/api/v2/businessrules/decisiontables/{tableId}/versions/{tableVersion}/rows/search" endpoint.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID} If a path parameter argument is not of the proper type.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETERS_TYPE_INVALID} If the query string parameters argument is not of the proper type.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETER_TYPE_INVALID} If a query string parameter is not of the proper type.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_REQUEST_BODY_TYPE_INVALID} If the request body argument is not of the proper type.
	 */
	postBusinessrulesDecisiontableVersionRowsSearch(tableId, tableVersion, query, body) {
		const endpointPath = "/api/v2/businessrules/decisiontables/{tableId}/versions/{tableVersion}/rows/search";
		const endpointMethod = "POST";

		// Check the path parameters
		if (this.#checkJSONSchemaType(tableId, "string") === false) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "tableId", "string");
		}

		if (this.#checkJSONSchemaType(tableVersion, "integer") === false) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "tableVersion", "integer");
		}

		// Check the query string parameters
		if (typeof query !== "object") {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETERS_TYPE_INVALID(endpointPath, endpointMethod, false);
		}

		if (query !== null) {
			if ("pageNumber" in query && this.#checkJSONSchemaType(query["pageNumber"], "string") === false) {
				throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "pageNumber", "string");
			}
			if ("pageSize" in query && this.#checkJSONSchemaType(query["pageSize"], "string") === false) {
				throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "pageSize", "string");
			}
		}

		// Check the body argument
		if (this.#checkJSONSchemaType(body, "object") === false || body === null) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_REQUEST_BODY_TYPE_INVALID(endpointPath, endpointMethod, "object", true);
		}

		const apiCallOptions = {};
		apiCallOptions.pathParameters = {};
		apiCallOptions.pathParameters.tableId = tableId;
		apiCallOptions.pathParameters.tableVersion = tableVersion;
		apiCallOptions.queryParameters = query;
		apiCallOptions.body = body;

		return this.#gcPlatformAPIClient.queueAPICall(endpointPath, endpointMethod, apiCallOptions);
	}

	/**
	 * Get a specific named core type.
	 * @async
	 * @param {string} coreTypeName - The core type's name
	 * @returns {Promise<HTTPResponse>} A promise that settles to the HTTP response of the call to the "/api/v2/businessrules/schemas/coretypes/{coreTypeName}" endpoint.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID} If a path parameter argument is not of the proper type.
	 */
	getBusinessrulesSchemasCoretype(coreTypeName) {
		const endpointPath = "/api/v2/businessrules/schemas/coretypes/{coreTypeName}";
		const endpointMethod = "GET";

		// Check the path parameters
		if (this.#checkJSONSchemaType(coreTypeName, "string") === false) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "coreTypeName", "string");
		}

		const apiCallOptions = {};
		apiCallOptions.pathParameters = {};
		apiCallOptions.pathParameters.coreTypeName = coreTypeName;

		return this.#gcPlatformAPIClient.queueAPICall(endpointPath, endpointMethod, apiCallOptions);
	}

	/**
	 * Get the core types from which all schemas are built.
	 * @async
	 * @returns {Promise<HTTPResponse>} A promise that settles to the HTTP response of the call to the "/api/v2/businessrules/schemas/coretypes" endpoint.
	 */
	getBusinessrulesSchemasCoretypes() {
		const endpointPath = "/api/v2/businessrules/schemas/coretypes";
		const endpointMethod = "GET";

		const apiCallOptions = {};

		return this.#gcPlatformAPIClient.queueAPICall(endpointPath, endpointMethod, apiCallOptions);
	}

	/**
	 * Get a schema
	 * @async
	 * @param {string} schemaId - Schema ID
	 * @returns {Promise<HTTPResponse>} A promise that settles to the HTTP response of the call to the "/api/v2/businessrules/schemas/{schemaId}" endpoint.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID} If a path parameter argument is not of the proper type.
	 */
	getBusinessrulesSchema(schemaId) {
		const endpointPath = "/api/v2/businessrules/schemas/{schemaId}";
		const endpointMethod = "GET";

		// Check the path parameters
		if (this.#checkJSONSchemaType(schemaId, "string") === false) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "schemaId", "string");
		}

		const apiCallOptions = {};
		apiCallOptions.pathParameters = {};
		apiCallOptions.pathParameters.schemaId = schemaId;

		return this.#gcPlatformAPIClient.queueAPICall(endpointPath, endpointMethod, apiCallOptions);
	}

	/**
	 * Update a schema
	 * @async
	 * @param {string} schemaId - Schema ID
	 * @param {BusinessRulesSchemaUpdateRequest} body - The body of the request. An empty object or null is allowed if the body is optional.
	 * @returns {Promise<HTTPResponse>} A promise that settles to the HTTP response of the call to the "/api/v2/businessrules/schemas/{schemaId}" endpoint.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID} If a path parameter argument is not of the proper type.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_REQUEST_BODY_TYPE_INVALID} If the request body argument is not of the proper type.
	 */
	putBusinessrulesSchema(schemaId, body) {
		const endpointPath = "/api/v2/businessrules/schemas/{schemaId}";
		const endpointMethod = "PUT";

		// Check the path parameters
		if (this.#checkJSONSchemaType(schemaId, "string") === false) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "schemaId", "string");
		}

		// Check the body argument
		if (this.#checkJSONSchemaType(body, "object") === false || body === null) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_REQUEST_BODY_TYPE_INVALID(endpointPath, endpointMethod, "object", true);
		}

		const apiCallOptions = {};
		apiCallOptions.pathParameters = {};
		apiCallOptions.pathParameters.schemaId = schemaId;
		apiCallOptions.body = body;

		return this.#gcPlatformAPIClient.queueAPICall(endpointPath, endpointMethod, apiCallOptions);
	}

	/**
	 * Delete a schema
	 * @async
	 * @param {string} schemaId - Schema ID
	 * @returns {Promise<HTTPResponse>} A promise that settles to the HTTP response of the call to the "/api/v2/businessrules/schemas/{schemaId}" endpoint.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID} If a path parameter argument is not of the proper type.
	 */
	deleteBusinessrulesSchema(schemaId) {
		const endpointPath = "/api/v2/businessrules/schemas/{schemaId}";
		const endpointMethod = "DELETE";

		// Check the path parameters
		if (this.#checkJSONSchemaType(schemaId, "string") === false) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "schemaId", "string");
		}

		const apiCallOptions = {};
		apiCallOptions.pathParameters = {};
		apiCallOptions.pathParameters.schemaId = schemaId;

		return this.#gcPlatformAPIClient.queueAPICall(endpointPath, endpointMethod, apiCallOptions);
	}

	/**
	 * Get a list of schemas.
	 * @async
	 * @returns {Promise<HTTPResponse>} A promise that settles to the HTTP response of the call to the "/api/v2/businessrules/schemas" endpoint.
	 */
	getBusinessrulesSchemas() {
		const endpointPath = "/api/v2/businessrules/schemas";
		const endpointMethod = "GET";

		const apiCallOptions = {};

		return this.#gcPlatformAPIClient.queueAPICall(endpointPath, endpointMethod, apiCallOptions);
	}

	/**
	 * Create a schema
	 * @async
	 * @param {BusinessRulesSchemaCreateRequest} body - The body of the request. An empty object or null is allowed if the body is optional.
	 * @returns {Promise<HTTPResponse>} A promise that settles to the HTTP response of the call to the "/api/v2/businessrules/schemas" endpoint.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_REQUEST_BODY_TYPE_INVALID} If the request body argument is not of the proper type.
	 */
	postBusinessrulesSchemas(body) {
		const endpointPath = "/api/v2/businessrules/schemas";
		const endpointMethod = "POST";

		// Check the body argument
		if (this.#checkJSONSchemaType(body, "object") === false || body === null) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_REQUEST_BODY_TYPE_INVALID(endpointPath, endpointMethod, "object", true);
		}

		const apiCallOptions = {};
		apiCallOptions.body = body;

		return this.#gcPlatformAPIClient.queueAPICall(endpointPath, endpointMethod, apiCallOptions);
	}

	/**
	 * @description Checks that a value is of the proper JSON schema type
	 * @param {*} value - The value to check
	 * @param {string} jsonSchemaType - The JSON schema type to check against
	 * @returns {boolean} Returns true if the value is of the proper JSON schema type, false otherwise
	 */
	#checkJSONSchemaType(value, jsonSchemaType) {
		const PASSTHROUGH_JSON_SCHEMA_TYPES = ["boolean", "number", "string", "object"];

		// Check if the type is a passthrough type
		if (PASSTHROUGH_JSON_SCHEMA_TYPES.includes(jsonSchemaType)) {
			return typeof value === jsonSchemaType;
		}

		// Check if the type is an integer
		if (jsonSchemaType === "integer") {
			return Number.isInteger(value);
		}

		// Check if the type is an array
		if (jsonSchemaType === "array") {
			return Array.isArray(value);
		}

		// Check if the type is null
		if (jsonSchemaType === "null") {
			return value === null;
		}

		// Otherwise, return false
		return false;
	}
}

export { BusinessRulesAPI };