/**
 * Chatbot Interactions
 * @module gc-platform-api-textbots
 * @license MIT
 */

// This file was automatically generated by the Generate Genesys Cloud Platform API classes utility on 2025-11-26T23:43:17.601Z

// TODO: Implement JSON schema verification for input and output objects
// TODO: Implement HTTP response typedefs

// Set strict mode
"use strict";

// Errors
import { errors } from "../gc-platform-api-client-errors.js";

// Symbols
import { symbols } from "../gc-platform-api-client-symbols.js";

/** @typedef {import("../gc-platform-api-client-class.js").GCPlatformAPIClient} GCPlatformAPIClient */
/** @typedef {import("@jfabello/http-client").HTTPResponse} HTTPResponse */

/**
 * @typedef {object} AmazonLexRequest
 * @property {object} [requestAttributes] - AttributeName/AttributeValue pairs of User Defined Request Attributes to be sent to the amazon bot See - https://docs.aws.amazon.com/lex/latest/dg/context-mgmt.html#context-mgmt-request-attribs
 * @property {object} [sessionAttributes] - AttributeName/AttributeValue pairs of Session Attributes to be sent to the amazon bot. See - https://docs.aws.amazon.com/lex/latest/dg/context-mgmt.html#context-mgmt-session-attribs
 */
 
/**
 * Attachment object.
 * @typedef {object} ConversationContentAttachment
 * @property {string} [id] - Provider specific ID for attachment.
 * @property {string} mediaType - The type of attachment this instance represents.
 * @property {string} [url] - URL of the attachment.
 * @property {string} [mime] - Attachment mime type (https://www.iana.org/assignments/media-types/media-types.xhtml).
 * @property {string} [text] - Text associated with attachment such as an image caption.
 * @property {string} [sha256] - Secure hash of the attachment content.
 * @property {string} [filename] - Suggested file name for attachment.
 * @property {number} [contentSizeBytes] - Size in bytes of the attachment content.
 */
 
/**
 * Button response object representing the click of a structured message button, such as a quick reply.
 * @typedef {object} ConversationContentButtonResponse
 * @property {string} [originatingMessageId] - Reference to the ID of the original message (e.g., list picker) this button response is replying to.
 * @property {string} [type] - Describes the button that resulted in the Button Response.
 * @property {string} text - The response text from the button click.
 * @property {string} payload - The response payload associated with the clicked button.
 */
 
/**
 * Card content object.
 * @typedef {object} ConversationContentCard
 * @property {string} title - Text to show in the title.
 * @property {string} [description] - Text to show in the description.
 * @property {string} [image] - URL of an image.
 * @property {string} [video] - URL of a video.
 * @property {ConversationContentCardAction} [defaultAction] - The default button action.
 * @property {ConversationContentCardAction[]} actions - An array of action objects.
 */
 
/**
 * A card action that a user can take.
 * @typedef {object} ConversationContentCardAction
 * @property {string} [type] - Describes the type of action.
 * @property {string} [text] - The response text from the button click.
 * @property {string} [payload] - Text to be returned as the payload from a ButtonResponse when a button is clicked. The payload and text are a combination which will have to be unique across each card and carousel in order to determine which button was clicked in that card or carousel.
 * @property {string} [url] - A URL of a web page to direct the user to.
 */
 
/**
 * Carousel content object.
 * @typedef {object} ConversationContentCarousel
 * @property {ConversationContentCard[]} cards - An array of card objects.
 */
 
/**
 * DateTimePicker content object.
 * @typedef {object} ConversationContentDatePicker
 * @property {string} [id] - Optional unique identifier to help map component replies to form messages where multiple DatePickers can be present.
 * @property {string} [title] - Text to show in the title.
 * @property {string} [subtitle] - Text to show in the description.
 * @property {string} [imageUrl] - URL of an image
 * @property {string} [dateMinimum] - The minimum Date Enabled in the datepicker calendar, format: ISO 8601.
 * @property {string} [dateMaximum] - The maximum Date Enabled in the datepicker calendar, format: ISO 8601.
 * @property {ConversationContentLocation} [location] - Location of the event.
 * @property {ConversationContentDatePickerAvailableTime[]} [availableTimes] - An array of available times objects.
 * @property {string} [dateDisplayFormat] - The format the date should be presented to the end user.
 */
 
/**
 * A datetimepicker available time that a user can take.
 * @typedef {object} ConversationContentDatePickerAvailableTime
 * @property {number} [duration] - The duration of the scheduling event in seconds.
 * @property {string} [dateTime] - The date and time of the event being scheduled. Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss[.mmm]Z
 */
 
/**
 * Form content object.
 * @typedef {object} ConversationContentForm
 * @property {ConversationContentIntroduction} [introduction] - The intro component, used to give an intro into what the form entails
 * @property {ConversationFormPage[]} [formPages] - Form pages
 * @property {ConversationContentReceivedReplyMessage} [receivedMessage] - The message prompt to fill out the form received.
 * @property {ConversationContentReceivedReplyMessage} [replyMessage] - The reply message after the user has filled out the form received.
 * @property {boolean} [showSummary] - Show summary at end of form submission.
 * @property {ConversationFormResponseComponent[]} [response] - Content of the payload included in the Form response.
 * @property {string} [originatingMessageId] - Reference to the ID of the original message.
 * @property {string} cannedResponseId - The id of the canned response which was used to create the form.
 */
 
/**
 * Single or multiline text input component.
 * @typedef {object} ConversationContentInput
 * @property {string} [id] - Unique identifier for the input
 * @property {string} [title] - The main text displayed for the input field(s).
 * @property {string} [subtitle] - Additional text providing more details about the input field(s).
 * @property {string} [placeholderText] - Placeholder text for input field(s).
 * @property {boolean} isRequired - Whether the input field(s) are required to be filled in.
 * @property {boolean} isMultipleLine - Whether the input should allow multiple lines of text.
 * @property {string} [keyboardType] - Type of keyboard to be shown.
 * @property {string} [autoCompleteType] - A string value representing the keyboard and system information about the expected semantic meaning for the content that users enter.
 */
 
/**
 * InteractiveApplication content object.
 * @typedef {object} ConversationContentInteractiveApplication
 * @property {string} [name] - The name of the message app.
 * @property {string} [url] - Contains the data that is sent to the message app.
 * @property {ConversationContentReceivedReplyMessage} [receivedMessage] - The message displayed in the received message bubble.
 * @property {ConversationContentReceivedReplyMessage} [replyMessage] - The message displayed in the reply message bubble.
 */
 
/**
 * Introduction content object.
 * @typedef {object} ConversationContentIntroduction
 * @property {string} title - Text to show in the title.
 * @property {string} [subtitle] - Text to show in the subtitle.
 * @property {string} [imageUrl] - URL of an image.
 * @property {string} buttonText - Text to show on the button.
 */
 
/**
 * Item included in an order.
 * @typedef {object} ConversationContentLineItem
 * @property {string} name - The display name for the item.
 * @property {number} price - The price of the item.
 * @property {string} [description] - Additional details about the item (e.g. the length of time to deliver for shipping options).
 * @property {string} [identifier] - A client defined value used to identify the item.
 */
 
/**
 * List Picker object for presenting multiple sections of selectable items.
 * @typedef {object} ConversationContentListPicker
 * @property {string} [id] - Optional unique identifier to help map component replies to form messages where multiple ListPickers can be present.
 * @property {ConversationContentListPickerSection[]} [sections] - An array of sections in the List Picker.
 * @property {ConversationContentReceivedReplyMessage} [replyMessage] - The reply message after the user has selected the options from the List Picker.
 * @property {ConversationContentReceivedReplyMessage} [receivedMessage] - The message prompt to select options in the List Picker sections.
 */
 
/**
 * Represents a selectable item in a list picker.
 * @typedef {object} ConversationContentListPickerItem
 * @property {string} [id] - Unique identifier for the list picker item
 * @property {string} [title] - The main text displayed for the item.
 * @property {string} [subtitle] - Additional text providing more details about the item.
 * @property {string} [imageUrl] - URL of an image to be displayed alongside the item.
 */
 
/**
 * List Picker object for presenting a section of selectable items.
 * @typedef {object} ConversationContentListPickerSection
 * @property {string} [title] - Required title for the section.
 * @property {boolean} [multipleSelection] - Whether multiple items can be selected in this section.
 * @property {ConversationContentListPickerItem[]} [items] - List of items to choice from in the section
 */
 
/**
 * Location object.
 * @typedef {object} ConversationContentLocation
 * @property {string} [url] - URL of the Location.
 * @property {string} [address] - Location postal address.
 * @property {string} [text] - Location name.
 * @property {number} [latitude] - Latitude of the location.
 * @property {number} [longitude] - Longitude of the location.
 */
 
/**
 * Template notification object.
 * @typedef {object} ConversationContentNotificationTemplate
 * @property {string} [id] - The identifier of the message template in 'your-namespace@your-template-id/name' format. For External vendor (e.g WhatsApp), 'your-namespace@your-template-name'. For GenesysCloud canned response message template use 'cannedresponse' as your-namespace and use response ID as your-template-id (e.g. response ID=1234 then 'cannedresponse@1234')
 * @property {string} [language] - Template language.
 * @property {ConversationNotificationTemplateHeader} [header] - The template header.
 * @property {ConversationNotificationTemplateBody} body - The template body.
 * @property {ConversationNotificationTemplateButton[]} [buttons] - Template buttons
 * @property {ConversationNotificationTemplateFooter} [footer] - The template footer.
 */
 
/**
 * Payment Request object used to request payment from a customer.
 * @typedef {object} ConversationContentPaymentRequest
 * @property {string} paymentPlatform - The payment platform being used (e.g. Apple Pay)
 * @property {string} countryCode - The merchant's two-letter ISO 3166 country code.
 * @property {string} currencyCode - The three-letter ISO 4217 currency code for the payment.
 * @property {number} orderTotal - The total price of the order.
 * @property {ConversationContentLineItem[]} [lineItems] - The items that make up the order.
 * @property {ConversationContentLineItem[]} [shippingOptions] - The available shipping options.
 * @property {ConversationContentRequiredContactField[]} [requiredContactFields] - Contact fields required to complete the order.
 * @property {ConversationContentReceivedReplyMessage} [receivedMessage] - The message prompt to complete a payment transaction.
 * @property {ConversationContentReceivedReplyMessage} [replyMessage] - The reply message after the user has completed the payment transaction.
 */
 
/**
 * Payment response object representing the status of a payment transaction.
 * @typedef {object} ConversationContentPaymentResponse
 * @property {string} originatingMessageId - Reference to the ID of the original payment request message this response is for.
 * @property {string} paymentStatus - The status of the payment transaction.
 * @property {string} [failureReason] - The reason the payment request failed.
 */
 
/**
 * A Push object
 * @typedef {object} ConversationContentPush
 * @property {string} deviceType - The device type used to send the push notification
 * @property {string} deviceTokenId - Unique Id of the device token
 * @property {string} deviceToken - device token from the notification provider
 * @property {ConversationPushFailedMessageReferences[]} failedMessages - MessageIds failed to be sent which trigger the push event
 * @property {ConversationPushNotificationMessageLabel} notificationMessage - Title and body localized according to deployment
 * @property {ConversationPushProviderIntegration} pushProviderIntegration - Push provider integrations details configured on the deployment
 * @property {number} expiration - The time to live of the pushed message
 */
 
/**
 * Quick reply object.
 * @typedef {object} ConversationContentQuickReply
 * @property {string} text - Text to show inside the quick reply. This is also used as the response text after clicking on the quick reply.
 * @property {string} payload - Content of the payload included in the quick reply response. Could be an ID identifying the quick reply response.
 * @property {string} [image] - URL of an image associated with the quick reply.
 * @property {string} [action] - Specifies the type of action that is triggered upon clicking the quick reply.
 * @property {string} [summaryText] - Summary of what the quick reply relates to.
 */
 
/**
 * Quick reply object V2.
 * @typedef {object} ConversationContentQuickReplyV2
 * @property {string} title - Text to show as the title of the quick reply.
 * @property {ConversationContentQuickReply[]} actions - An array of quick reply objects.
 */
 
/**
 * User reaction to public message.
 * @typedef {object} ConversationContentReaction
 * @property {string} [reactionType] - Type of reaction.
 * @property {number} count - Number of users that reacted this way to the message.
 */
 
/**
 * ReceivedReplyMessage content object.
 * @typedef {object} ConversationContentReceivedReplyMessage
 * @property {string} [header] - Text to show in the header.
 * @property {string} [title] - Text to show in the title.
 * @property {string} [subtitle] - Text to show in the subtitle.
 * @property {string} [buttonLabel] - Text to show on the button label.
 * @property {string} [imageUrl] - URL of an image.
 */
 
/**
 * Contact fields a merchant requires to complete a payment request.
 * @typedef {object} ConversationContentRequiredContactField
 * @property {string} contactField - The name of the contact field
 */
 
/**
 * An ephemeral story.
 * @typedef {object} ConversationContentStory
 * @property {string} [type] - Type of ephemeral story attachment.
 * @property {string} [url] - URL to the ephemeral story.
 * @property {string} [replyToId] - ID of the ephemeral story being replied to.
 */
 
/**
 * Message content element containing text only.
 * @typedef {object} ConversationContentText
 * @property {string} [type] - Type of text content (Deprecated).
 * @property {string} body - Text to be shown for this content element.
 */
 
/**
 * Wheel Picker object for representing single selection of selectable items.
 * @typedef {object} ConversationContentWheelPicker
 * @property {string} [id] - Optional unique identifier to help map component replies to form messages where multiple Wheel Pickers can be present.
 * @property {ConversationContentWheelPickerItem[]} items - The main text displayed for the item.
 */
 
/**
 * Represents a selectable item in a Wheel Picker
 * @typedef {object} ConversationContentWheelPickerItem
 * @property {string} id - Unique identifier for the wheel picker item
 * @property {string} title - The main text displayed for the item.
 * @property {string} [value] - The value of the item.
 */
 
/**
 * Form page object.
 * @typedef {object} ConversationFormPage
 * @property {string} title - Text to show in the title.
 * @property {string} subtitle - Text to show in the subtitle.
 * @property {ConversationFormPageComponent[]} [pageComponents] - Page components in this form page.
 */
 
/**
 * Form component element. Examples include: List Picker, Date Picker, Wheel Picker and Input text.
 * @typedef {object} ConversationFormPageComponent
 * @property {string} [formComponentType] - Type of this form component element
 * @property {ConversationContentDatePicker} [datePicker] - Date Picker content.
 * @property {ConversationContentWheelPicker} [wheelPicker] - Wheel Picker content.
 * @property {ConversationContentListPicker} [listPicker] - List Picker content.
 * @property {ConversationContentInput} [input] - Input content.
 */
 
/**
 * A response component from a form
 * @typedef {object} ConversationFormResponseComponent
 * @property {string} id - The id of the component in the original message.
 * @property {ConversationFormResponseContent} component - The content object capturing component response from the original message.
 */
 
/**
 * Message content element for form responses
 * @typedef {object} ConversationFormResponseContent
 * @property {string} [contentType] - Type of this content element.
 * @property {ConversationContentButtonResponse} [buttonResponse] - Button response content.
 */
 
/**
 * Message content element. If contentType = "Attachment" only one item is allowed.
 * @typedef {object} ConversationMessageContent
 * @property {string} contentType - Type of this content element.
 * @property {ConversationContentLocation} [location] - Location content.
 * @property {ConversationContentAttachment} [attachment] - Attachment content.
 * @property {ConversationContentQuickReply} [quickReply] - Quick reply content.
 * @property {ConversationContentButtonResponse} [buttonResponse] - Button response content.
 * @property {ConversationContentNotificationTemplate} [template] - Template notification content.
 * @property {ConversationContentStory} [story] - Ephemeral story content.
 * @property {ConversationContentCard} [card] - Card content
 * @property {ConversationContentCarousel} [carousel] - Carousel content
 * @property {ConversationContentText} [text] - Text content.
 * @property {ConversationContentQuickReplyV2} [quickReplyV2] - Quick reply V2 content.
 * @property {ConversationContentReaction[]} [reactions] - A set of reactions to a message.
 * @property {ConversationContentDatePicker} [datePicker] - Date picker content.
 * @property {ConversationContentInteractiveApplication} [interactiveApplication] - InteractiveApplication content.
 * @property {ConversationContentListPicker} [listPicker] - List picker content.
 * @property {ConversationContentPaymentRequest} [paymentRequest] - Payment request content.
 * @property {ConversationContentPaymentResponse} [paymentResponse] - Payment response content.
 * @property {ConversationContentPush} [push] - Push content.
 * @property {ConversationContentForm} [form] - Form content.
 */
 
/**
 * Template body object.
 * @typedef {object} ConversationNotificationTemplateBody
 * @property {string} [text] - Body text. For WhatsApp, ignored.
 * @property {ConversationNotificationTemplateParameter[]} parameters - Template parameters for placeholders in template.
 */
 
/**
 * Template button object
 * @typedef {object} ConversationNotificationTemplateButton
 * @property {string} type - Specifies the type of the button.
 * @property {string} [text] - Button text message.
 * @property {number} index - index of the button in the list.
 * @property {string} [phoneNumber] - Button phone number.
 * @property {string} [url] - Button URL link.
 * @property {ConversationNotificationTemplateParameter[]} [parameters] - Template parameters for placeholders in the button.
 */
 
/**
 * Template footer object.
 * @typedef {object} ConversationNotificationTemplateFooter
 * @property {string} [text] - Footer text. For WhatsApp, ignored.
 */
 
/**
 * Template header object.
 * @typedef {object} ConversationNotificationTemplateHeader
 * @property {string} type - Template header type.
 * @property {string} [text] - Header text. For WhatsApp, ignored.
 * @property {ConversationContentAttachment} [media] - Media template header image.
 * @property {ConversationNotificationTemplateParameter[]} [parameters] - Template parameters for placeholders in template.
 */
 
/**
 * Template parameters for placeholders in template.
 * @typedef {object} ConversationNotificationTemplateParameter
 * @property {string} [name] - Parameter name.
 * @property {string} text - Parameter text value.
 */
 
/**
 * References of failed messages requiring a push.
 * @typedef {object} ConversationPushFailedMessageReferences
 * @property {string} id - Unique ID of the message.
 */
 
/**
 * A Push notification message label.
 * @typedef {object} ConversationPushNotificationMessageLabel
 * @property {string} title - Title to use in the push for each language configured in the deploymentId
 * @property {string} body - Body to use in the push for each language configured in the deploymentId
 */
 
/**
 * A Push provider integration.
 * @typedef {object} ConversationPushProviderIntegration
 * @property {string} id - Genesys Cloud Integration ID
 * @property {string} provider - Type of the integration
 */
 
/**
 * @typedef {object} GenesysBotConnector
 * @property {object} [queryParameters] - User defined name/value parameters passed to the BotConnector bot.
 */
 
/**
 * @typedef {object} GoogleDialogflowCustomSettings
 * @property {string} [environment] - If set this environment will be used to initiate the dialogflow bot, otherwise the default configuration will be used.  See https://cloud.google.com/dialogflow/docs/agents-versions
 * @property {string} [eventName] - If set this eventName will be used to initiate the dialogflow bot rather than language processing on the input text.  See https://cloud.google.com/dialogflow/es/docs/events-overview
 * @property {object} [webhookQueryParameters] - Parameters passed to the fulfillment webhook of the bot (if any).
 * @property {object} [eventInputParameters] - Parameters passed to the event input of the bot.
 */
 
/**
 * @typedef {object} NuanceMixDlgSettings
 * @property {string} [channelId] - The Nuance channel ID to use when launching the Nuance bot, which must one of the code names of the bot's registered input channels.
 * @property {object} [inputParameters] - Name/value pairs of input variables to be sent to the Nuance bot. The values must be in the appropriate format for the variable's type (see https://docs.mix.nuance.com/dialog-grpc/v1/#simple-variable-types for help)
 */
 
/**
 * @typedef {object} PostTextMessage
 * @property {string} type - Message type
 * @property {string} [text] - Message text. If type is structured, used as fallback for clients that do not support particular structured content
 * @property {ConversationMessageContent[]} [content] - A list of content elements in message
 */
 
/**
 * @typedef {object} PostTextRequest
 * @property {string} botId - ID of the bot to send the text to.
 * @property {string} [botAlias] - Alias/Version of the bot
 * @property {string} integrationId - the integration service id for the bot's credentials
 * @property {string} botSessionId - GUID for this bot's session
 * @property {PostTextMessage} postTextMessage - Message to send to the bot
 * @property {string} [languageCode] - The language code the bot will run under
 * @property {number} [botSessionTimeoutMinutes] - Override timeout for the bot session. This should be greater than 10 minutes.
 * @property {string[]} [botChannels] - The channels this bot is utilizing
 * @property {string} [botCorrelationId] - Id for tracking the activity - this will be returned in the response
 * @property {string} [messagingPlatformType] - If the channels list contains a 'Messaging' item and the messaging platform is known, include it here to get accurate analytics
 * @property {AmazonLexRequest} [amazonLexRequest] - Provider specific settings, if any
 * @property {GoogleDialogflowCustomSettings} [googleDialogflow] - Provider specific settings, if any
 * @property {GenesysBotConnector} [genesysBotConnector] - Provider specific settings, if any
 * @property {NuanceMixDlgSettings} [nuanceMixDlg] - Provider specific settings, if any
 */
 
/**
 * Channel information relevant to a bot flow.
 * @typedef {object} TextBotChannel
 * @property {string} name - The name of the channel.
 * @property {string[]} inputModes - The input modes for the channel.
 * @property {string[]} outputModes - The output modes for the channel.
 * @property {TextBotUserAgent} userAgent - Information about the end user agent calling the bot flow.
 */
 
/**
 * Settings for an input event to the bot flow indicating an error has occurred.
 * @typedef {object} TextBotErrorInputEvent
 * @property {string} code - The error code.
 * @property {string} message - The error message.
 */
 
/**
 * Description of the Bot Flow.
 * @typedef {object} TextBotFlow
 * @property {string} id - The Bot Flow ID.
 */
 
/**
 * Settings for launching an instance of a bot flow.
 * @typedef {object} TextBotFlowLaunchRequest
 * @property {TextBotFlow} flow - Specifies which Bot Flow to launch.
 * @property {string} externalSessionId - The ID of the external session that is associated with the bot flow.
 * @property {string} [conversationId] - A conversation ID to associate with the bot flow, if available.
 * @property {TextBotInputOutputData} [inputData] - Input values to the flow. Valid values are defined by the flow's input JSON schema.
 * @property {TextBotChannel} channel - Channel information relevant to the bot flow.
 * @property {string} [language] - The language that the bot will use in the session. Validated against list of supported languages and if the value is omitted or is invalid, the default language will be used.
 */
 
/**
 * Settings for a turn request to a bot flow.
 * @typedef {object} TextBotFlowTurnRequest
 * @property {TextBotTurnReference} [previousTurn] - The reference to a previous turn if appropriate, used to avoid race conditions.
 * @property {string} inputEventType - Indicates the type of input event being requested. If appropriate, fill out the matching user input object details on this request.
 * @property {TextBotUserInputEvent} [inputEventUserInput] - The data for the input event of this turn if it is a user input event. Only one inputEvent may be set.
 * @property {TextBotErrorInputEvent} [inputEventError] - The data for the input event of this turn if it is an error event. Only one inputEvent may be set.
 */
 
/**
 * Input/Output data related to a bot flow which is exiting gracefully.
 * @typedef {object} TextBotInputOutputData
 * @property {object} variables - The input/output variables using the format as appropriate for the variable data type in the flow definition.
 */
 
/**
 * Data for a single bot flow transcript.
 * @typedef {object} TextBotTranscript
 * @property {string} text - The text of the transcript item.
 * @property {number} [confidence] - The confidence factor, expressed as a decimal between 0.0 and 1.0, of the transcript item.
 */
 
/**
 * A reference to a bot flow turn.
 * @typedef {object} TextBotTurnReference
 * @property {string} id - The id of the turn.
 */
 
/**
 * Information about the caller executing a bot flow.
 * @typedef {object} TextBotUserAgent
 * @property {string} name - The name of the user agent.
 */
 
/**
 * User input data used in a bot flow turn.
 * @typedef {object} TextBotUserInputAlternative
 * @property {TextBotTranscript} transcript - The user input transcript.
 */
 
/**
 * Settings for an input event to the bot flow indicating user input is available.
 * @typedef {object} TextBotUserInputEvent
 * @property {string} mode - The input mode.
 * @property {TextBotUserInputAlternative[]} alternatives - The input alternatives.
 */
 

/**
 * Textbots - Chatbot Interactions
 * @class Textbots
 */
class TextbotsAPI {
	// Private instance properties
	#gcPlatformAPIClient = null;

	/**
	 * Constructor for the Textbots class
	 * @constructor
	 * @param {GCPlatformAPIClient} gcPlatformAPIClient - The Genesys Cloud Platform API client instance.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_INSTANCE_TYPE_INVALID} If the Genesys Cloud Platform API client instance argument is not an object.
	 */
	constructor(gcPlatformAPIClient) {
		// Check the Genesys Cloud Platform API client instance argument
		if (typeof gcPlatformAPIClient !== "object" || symbols.GCPlatformAPIClient in gcPlatformAPIClient === false) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_INSTANCE_TYPE_INVALID();
		}

		// Initialize the instance properties
		this.#gcPlatformAPIClient = gcPlatformAPIClient;
	}

	/**
	 * Issue a bot flow turn event
	 * @async
	 * @param {string} sessionId - The bot flow session ID, typically obtained from 'POST /api/v2/textbots/botflows/sessions'
	 * @param {TextBotFlowTurnRequest} body - The body of the request. An empty object or null is allowed if the body is optional.
	 * @returns {Promise<HTTPResponse>} A promise that settles to the HTTP response of the call to the "/api/v2/textbots/botflows/sessions/{sessionId}/turns" endpoint.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID} If a path parameter argument is not of the proper type.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_REQUEST_BODY_TYPE_INVALID} If the request body argument is not of the proper type.
	 */
	postTextbotsBotflowsSessionTurns(sessionId, body) {
		const endpointPath = "/api/v2/textbots/botflows/sessions/{sessionId}/turns";
		const endpointMethod = "POST";

		// Check the path parameters
		if (this.#checkJSONSchemaType(sessionId, "string") === false) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_PATH_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "sessionId", "string");
		}

		// Check the body argument
		if (this.#checkJSONSchemaType(body, "object") === false || body === null) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_REQUEST_BODY_TYPE_INVALID(endpointPath, endpointMethod, "object", true);
		}

		const apiCallOptions = {};
		apiCallOptions.pathParameters = {};
		apiCallOptions.pathParameters.sessionId = sessionId;
		apiCallOptions.body = body;

		return this.#gcPlatformAPIClient.queueAPICall(endpointPath, endpointMethod, apiCallOptions);
	}

	/**
	 * Create an execution instance of a bot flow definition.
	 * @async
	 * @param {TextBotFlowLaunchRequest} body - The body of the request. An empty object or null is allowed if the body is optional.
	 * @returns {Promise<HTTPResponse>} A promise that settles to the HTTP response of the call to the "/api/v2/textbots/botflows/sessions" endpoint.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_REQUEST_BODY_TYPE_INVALID} If the request body argument is not of the proper type.
	 */
	postTextbotsBotflowsSessions(body) {
		const endpointPath = "/api/v2/textbots/botflows/sessions";
		const endpointMethod = "POST";

		// Check the body argument
		if (this.#checkJSONSchemaType(body, "object") === false || body === null) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_REQUEST_BODY_TYPE_INVALID(endpointPath, endpointMethod, "object", true);
		}

		const apiCallOptions = {};
		apiCallOptions.body = body;

		return this.#gcPlatformAPIClient.queueAPICall(endpointPath, endpointMethod, apiCallOptions);
	}

	/**
	 * Send an intent to a bot to start a dialog/interact with it via text
	 * @async
	 * @param {PostTextRequest} body - The body of the request. An empty object or null is allowed if the body is optional.
	 * @returns {Promise<HTTPResponse>} A promise that settles to the HTTP response of the call to the "/api/v2/textbots/bots/execute" endpoint.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_REQUEST_BODY_TYPE_INVALID} If the request body argument is not of the proper type.
	 */
	postTextbotsBotsExecute(body) {
		const endpointPath = "/api/v2/textbots/bots/execute";
		const endpointMethod = "POST";

		// Check the body argument
		if (this.#checkJSONSchemaType(body, "object") === false || body === null) {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_REQUEST_BODY_TYPE_INVALID(endpointPath, endpointMethod, "object", true);
		}

		const apiCallOptions = {};
		apiCallOptions.body = body;

		return this.#gcPlatformAPIClient.queueAPICall(endpointPath, endpointMethod, apiCallOptions);
	}

	/**
	 * Find bots using the currently configured friendly name or ID.
	 * @async
	 * @param {object} query - The query string parameters for the request. An empty object or null is allowed if all query string parameters are optional.
	 * @param {string[]} [query.botType] -  Bot types
	 * @param {string} [query.botName] -  Bot name
	 * @param {string[]} [query.botId] -  Bot IDs. Maximum of 50
	 * @param {boolean} [query.virtualAgentEnabled] -  Include or exclude virtual agent flows, only applies to GenesysBotFlows or GenesysDigitalBotFlows
	 * @param {number} [query.pageSize] -  The maximum results to return. Maximum of 100
	 * @returns {Promise<HTTPResponse>} A promise that settles to the HTTP response of the call to the "/api/v2/textbots/bots/search" endpoint.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETERS_TYPE_INVALID} If the query string parameters argument is not of the proper type.
	 * @throws {ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETER_TYPE_INVALID} If a query string parameter is not of the proper type.
	 */
	getTextbotsBotsSearch(query) {
		const endpointPath = "/api/v2/textbots/bots/search";
		const endpointMethod = "GET";

		// Check the query string parameters
		if (typeof query !== "object") {
			throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETERS_TYPE_INVALID(endpointPath, endpointMethod, false);
		}

		if (query !== null) {
			if ("botType" in query && this.#checkJSONSchemaType(query["botType"], "array") === false) {
				throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "botType", "array");
			}
			if ("botName" in query && this.#checkJSONSchemaType(query["botName"], "string") === false) {
				throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "botName", "string");
			}
			if ("botId" in query && this.#checkJSONSchemaType(query["botId"], "array") === false) {
				throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "botId", "array");
			}
			if ("virtualAgentEnabled" in query && this.#checkJSONSchemaType(query["virtualAgentEnabled"], "boolean") === false) {
				throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "virtualAgentEnabled", "boolean");
			}
			if ("pageSize" in query && this.#checkJSONSchemaType(query["pageSize"], "integer") === false) {
				throw new errors.ERROR_GC_PLATFORM_API_CLIENT_API_CALL_QUERY_PARAMETER_TYPE_INVALID(endpointPath, endpointMethod, "pageSize", "integer");
			}
		}

		const apiCallOptions = {};
		apiCallOptions.queryParameters = query;

		return this.#gcPlatformAPIClient.queueAPICall(endpointPath, endpointMethod, apiCallOptions);
	}

	/**
	 * @description Checks that a value is of the proper JSON schema type
	 * @param {*} value - The value to check
	 * @param {string} jsonSchemaType - The JSON schema type to check against
	 * @returns {boolean} Returns true if the value is of the proper JSON schema type, false otherwise
	 */
	#checkJSONSchemaType(value, jsonSchemaType) {
		const PASSTHROUGH_JSON_SCHEMA_TYPES = ["boolean", "number", "string", "object"];

		// Check if the type is a passthrough type
		if (PASSTHROUGH_JSON_SCHEMA_TYPES.includes(jsonSchemaType)) {
			return typeof value === jsonSchemaType;
		}

		// Check if the type is an integer
		if (jsonSchemaType === "integer") {
			return Number.isInteger(value);
		}

		// Check if the type is an array
		if (jsonSchemaType === "array") {
			return Array.isArray(value);
		}

		// Check if the type is null
		if (jsonSchemaType === "null") {
			return value === null;
		}

		// Otherwise, return false
		return false;
	}
}

export { TextbotsAPI };